version: '3'
services:
  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: istory
      MYSQL_USER: dangtong
      MYSQL_PASSWORD: admin123
    ports:
      - "3306:3306"
    volumes:
    # 방금 생성한 mysql-data 볼륨과 연결
      - mysql-data:/var/lib/mysql
volumes:
# 컨테이너가 볼 수 있는 볼륨 이름
  mysql-data: 
    external: true
    name: mysql-data
